# Generated by Django 5.2 on 2026-04-23 19:29

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category_slug', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Slug only allows English characters, numbers, and hyphens.')])),
                ('category_image', models.ImageField(upload_to='category-image/')),
                ('category_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Slug only allows English characters, numbers, and hyphens.')])),
                ('read_time_min', models.PositiveIntegerField()),
                ('article_image', models.ImageField(upload_to='article-images/')),
                ('short_description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('avatar', models.ImageField(default='avatar-images/24eaa929-c37b-329a-80f2-5a72bd552305_rSRZN8L.jpg', upload_to='avatar-images/')),
                ('field_of_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('biography', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_date', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('citizenId', models.CharField(max_length=255)),
                ('avatar', models.URLField(max_length=500)),
                ('slug_level', models.PositiveIntegerField()),
                ('image_level', models.URLField(max_length=500)),
                ('content', models.TextField()),
                ('approved', models.BooleanField(default=True)),
                ('created_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('citizenId', models.CharField(max_length=255)),
                ('avatar', models.URLField(max_length=500)),
                ('slug_level', models.PositiveIntegerField()),
                ('image_level', models.URLField(max_length=500)),
                ('content', models.TextField()),
                ('approved', models.BooleanField(default=True)),
                ('created_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='articles.comment')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='articles.category')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.subcategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='articles', to='articles.tag'),
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('username', models.CharField(max_length=255)),
                ('citizenId', models.CharField(max_length=255)),
                ('created_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.article')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.comment')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.reply')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('citizenId', 'article'), name='unique_user_article_vote'), models.UniqueConstraint(fields=('citizenId', 'comment'), name='unique_user_comment_vote'), models.UniqueConstraint(fields=('citizenId', 'reply'), name='unique_user_reply_vote'), models.CheckConstraint(condition=models.Q(models.Q(('article__isnull', False), ('comment__isnull', True), ('reply__isnull', True)), models.Q(('article__isnull', True), ('comment__isnull', False), ('reply__isnull', True)), models.Q(('article__isnull', True), ('comment__isnull', True), ('reply__isnull', False)), _connector='OR'), name='exactly_one_target')],
            },
        ),
    ]
