// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: commercial.proto

package commercial

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_GetWallet_FullMethodName     = "/commercial.WalletService/GetWallet"
	WalletService_CreateWallet_FullMethodName  = "/commercial.WalletService/CreateWallet"
	WalletService_DeductBalance_FullMethodName = "/commercial.WalletService/DeductBalance"
	WalletService_AddBalance_FullMethodName    = "/commercial.WalletService/AddBalance"
	WalletService_LockBalance_FullMethodName   = "/commercial.WalletService/LockBalance"
	WalletService_UnlockBalance_FullMethodName = "/commercial.WalletService/UnlockBalance"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wallet Service - handles wallet operations
type WalletServiceClient interface {
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	DeductBalance(ctx context.Context, in *DeductBalanceRequest, opts ...grpc.CallOption) (*DeductBalanceResponse, error)
	AddBalance(ctx context.Context, in *AddBalanceRequest, opts ...grpc.CallOption) (*AddBalanceResponse, error)
	LockBalance(ctx context.Context, in *LockBalanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnlockBalance(ctx context.Context, in *UnlockBalanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, WalletService_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, WalletService_CreateWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) DeductBalance(ctx context.Context, in *DeductBalanceRequest, opts ...grpc.CallOption) (*DeductBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductBalanceResponse)
	err := c.cc.Invoke(ctx, WalletService_DeductBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) AddBalance(ctx context.Context, in *AddBalanceRequest, opts ...grpc.CallOption) (*AddBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBalanceResponse)
	err := c.cc.Invoke(ctx, WalletService_AddBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) LockBalance(ctx context.Context, in *LockBalanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_LockBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) UnlockBalance(ctx context.Context, in *UnlockBalanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_UnlockBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
//
// Wallet Service - handles wallet operations
type WalletServiceServer interface {
	GetWallet(context.Context, *GetWalletRequest) (*WalletResponse, error)
	CreateWallet(context.Context, *CreateWalletRequest) (*WalletResponse, error)
	DeductBalance(context.Context, *DeductBalanceRequest) (*DeductBalanceResponse, error)
	AddBalance(context.Context, *AddBalanceRequest) (*AddBalanceResponse, error)
	LockBalance(context.Context, *LockBalanceRequest) (*emptypb.Empty, error)
	UnlockBalance(context.Context, *UnlockBalanceRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) GetWallet(context.Context, *GetWalletRequest) (*WalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedWalletServiceServer) CreateWallet(context.Context, *CreateWalletRequest) (*WalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedWalletServiceServer) DeductBalance(context.Context, *DeductBalanceRequest) (*DeductBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeductBalance not implemented")
}
func (UnimplementedWalletServiceServer) AddBalance(context.Context, *AddBalanceRequest) (*AddBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBalance not implemented")
}
func (UnimplementedWalletServiceServer) LockBalance(context.Context, *LockBalanceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockBalance not implemented")
}
func (UnimplementedWalletServiceServer) UnlockBalance(context.Context, *UnlockBalanceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockBalance not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call pancis, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_CreateWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateWallet(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_DeductBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).DeductBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_DeductBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).DeductBalance(ctx, req.(*DeductBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_AddBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).AddBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_AddBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).AddBalance(ctx, req.(*AddBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_LockBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).LockBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_LockBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).LockBalance(ctx, req.(*LockBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_UnlockBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).UnlockBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_UnlockBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).UnlockBalance(ctx, req.(*UnlockBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commercial.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWallet",
			Handler:    _WalletService_GetWallet_Handler,
		},
		{
			MethodName: "CreateWallet",
			Handler:    _WalletService_CreateWallet_Handler,
		},
		{
			MethodName: "DeductBalance",
			Handler:    _WalletService_DeductBalance_Handler,
		},
		{
			MethodName: "AddBalance",
			Handler:    _WalletService_AddBalance_Handler,
		},
		{
			MethodName: "LockBalance",
			Handler:    _WalletService_LockBalance_Handler,
		},
		{
			MethodName: "UnlockBalance",
			Handler:    _WalletService_UnlockBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commercial.proto",
}

const (
	TransactionService_ListTransactions_FullMethodName     = "/commercial.TransactionService/ListTransactions"
	TransactionService_GetLatestTransaction_FullMethodName = "/commercial.TransactionService/GetLatestTransaction"
	TransactionService_CreateTransaction_FullMethodName    = "/commercial.TransactionService/CreateTransaction"
)

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Transaction Service - handles transaction history
type TransactionServiceClient interface {
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	GetLatestTransaction(ctx context.Context, in *GetLatestTransactionRequest, opts ...grpc.CallOption) (*LatestTransactionResponse, error)
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, TransactionService_ListTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetLatestTransaction(ctx context.Context, in *GetLatestTransactionRequest, opts ...grpc.CallOption) (*LatestTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatestTransactionResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetLatestTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, TransactionService_CreateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility.
//
// Transaction Service - handles transaction history
type TransactionServiceServer interface {
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	GetLatestTransaction(context.Context, *GetLatestTransactionRequest) (*LatestTransactionResponse, error)
	CreateTransaction(context.Context, *CreateTransactionRequest) (*Transaction, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionServiceServer struct{}

func (UnimplementedTransactionServiceServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedTransactionServiceServer) GetLatestTransaction(context.Context, *GetLatestTransactionRequest) (*LatestTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) CreateTransaction(context.Context, *CreateTransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}
func (UnimplementedTransactionServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetLatestTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetLatestTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetLatestTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetLatestTransaction(ctx, req.(*GetLatestTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CreateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commercial.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTransactions",
			Handler:    _TransactionService_ListTransactions_Handler,
		},
		{
			MethodName: "GetLatestTransaction",
			Handler:    _TransactionService_GetLatestTransaction_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _TransactionService_CreateTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commercial.proto",
}

const (
	ReferralService_ProcessReferral_FullMethodName = "/commercial.ReferralService/ProcessReferral"
)

// ReferralServiceClient is the client API for ReferralService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Referral Service - processes referral commissions after successful payments
type ReferralServiceClient interface {
	ProcessReferral(ctx context.Context, in *ProcessReferralRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type referralServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReferralServiceClient(cc grpc.ClientConnInterface) ReferralServiceClient {
	return &referralServiceClient{cc}
}

func (c *referralServiceClient) ProcessReferral(ctx context.Context, in *ProcessReferralRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ReferralService_ProcessReferral_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReferralServiceServer is the server API for ReferralService service.
// All implementations must embed UnimplementedReferralServiceServer
// for forward compatibility.
//
// Referral Service - processes referral commissions after successful payments
type ReferralServiceServer interface {
	ProcessReferral(context.Context, *ProcessReferralRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedReferralServiceServer()
}

// UnimplementedReferralServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReferralServiceServer struct{}

func (UnimplementedReferralServiceServer) ProcessReferral(context.Context, *ProcessReferralRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessReferral not implemented")
}
func (UnimplementedReferralServiceServer) mustEmbedUnimplementedReferralServiceServer() {}
func (UnimplementedReferralServiceServer) testEmbeddedByValue()                         {}

// UnsafeReferralServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReferralServiceServer will
// result in compilation errors.
type UnsafeReferralServiceServer interface {
	mustEmbedUnimplementedReferralServiceServer()
}

func RegisterReferralServiceServer(s grpc.ServiceRegistrar, srv ReferralServiceServer) {
	// If the following call pancis, it indicates UnimplementedReferralServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReferralService_ServiceDesc, srv)
}

func _ReferralService_ProcessReferral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessReferralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServiceServer).ProcessReferral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferralService_ProcessReferral_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServiceServer).ProcessReferral(ctx, req.(*ProcessReferralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReferralService_ServiceDesc is the grpc.ServiceDesc for ReferralService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReferralService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commercial.ReferralService",
	HandlerType: (*ReferralServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessReferral",
			Handler:    _ReferralService_ProcessReferral_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commercial.proto",
}

const (
	UserVariableService_CreateUserVariables_FullMethodName = "/commercial.UserVariableService/CreateUserVariables"
)

// UserVariableServiceClient is the client API for UserVariableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserVariable Service - handles per-user commercial variables
type UserVariableServiceClient interface {
	CreateUserVariables(ctx context.Context, in *CreateUserVariablesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type userVariableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserVariableServiceClient(cc grpc.ClientConnInterface) UserVariableServiceClient {
	return &userVariableServiceClient{cc}
}

func (c *userVariableServiceClient) CreateUserVariables(ctx context.Context, in *CreateUserVariablesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserVariableService_CreateUserVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserVariableServiceServer is the server API for UserVariableService service.
// All implementations must embed UnimplementedUserVariableServiceServer
// for forward compatibility.
//
// UserVariable Service - handles per-user commercial variables
type UserVariableServiceServer interface {
	CreateUserVariables(context.Context, *CreateUserVariablesRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedUserVariableServiceServer()
}

// UnimplementedUserVariableServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserVariableServiceServer struct{}

func (UnimplementedUserVariableServiceServer) CreateUserVariables(context.Context, *CreateUserVariablesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserVariables not implemented")
}
func (UnimplementedUserVariableServiceServer) mustEmbedUnimplementedUserVariableServiceServer() {}
func (UnimplementedUserVariableServiceServer) testEmbeddedByValue()                             {}

// UnsafeUserVariableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserVariableServiceServer will
// result in compilation errors.
type UnsafeUserVariableServiceServer interface {
	mustEmbedUnimplementedUserVariableServiceServer()
}

func RegisterUserVariableServiceServer(s grpc.ServiceRegistrar, srv UserVariableServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserVariableServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserVariableService_ServiceDesc, srv)
}

func _UserVariableService_CreateUserVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserVariableServiceServer).CreateUserVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserVariableService_CreateUserVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserVariableServiceServer).CreateUserVariables(ctx, req.(*CreateUserVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserVariableService_ServiceDesc is the grpc.ServiceDesc for UserVariableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserVariableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commercial.UserVariableService",
	HandlerType: (*UserVariableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserVariables",
			Handler:    _UserVariableService_CreateUserVariables_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commercial.proto",
}

const (
	WalletHistoryService_GetWalletHistorySummary_FullMethodName = "/commercial.WalletHistoryService/GetWalletHistorySummary"
	WalletHistoryService_GetWalletHistoryChart_FullMethodName   = "/commercial.WalletHistoryService/GetWalletHistoryChart"
)

// WalletHistoryServiceClient is the client API for WalletHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WalletHistoryService — public citizen wallet income/spending history.
// Auth is skipped; privacy is applied by the gateway via allowed_assets,
// and the service still returns privacy_restricted stubs for requested hidden assets.
type WalletHistoryServiceClient interface {
	GetWalletHistorySummary(ctx context.Context, in *GetWalletHistorySummaryRequest, opts ...grpc.CallOption) (*GetWalletHistorySummaryResponse, error)
	GetWalletHistoryChart(ctx context.Context, in *GetWalletHistoryChartRequest, opts ...grpc.CallOption) (*GetWalletHistoryChartResponse, error)
}

type walletHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletHistoryServiceClient(cc grpc.ClientConnInterface) WalletHistoryServiceClient {
	return &walletHistoryServiceClient{cc}
}

func (c *walletHistoryServiceClient) GetWalletHistorySummary(ctx context.Context, in *GetWalletHistorySummaryRequest, opts ...grpc.CallOption) (*GetWalletHistorySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletHistorySummaryResponse)
	err := c.cc.Invoke(ctx, WalletHistoryService_GetWalletHistorySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletHistoryServiceClient) GetWalletHistoryChart(ctx context.Context, in *GetWalletHistoryChartRequest, opts ...grpc.CallOption) (*GetWalletHistoryChartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletHistoryChartResponse)
	err := c.cc.Invoke(ctx, WalletHistoryService_GetWalletHistoryChart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletHistoryServiceServer is the server API for WalletHistoryService service.
// All implementations must embed UnimplementedWalletHistoryServiceServer
// for forward compatibility.
//
// WalletHistoryService — public citizen wallet income/spending history.
// Auth is skipped; privacy is applied by the gateway via allowed_assets,
// and the service still returns privacy_restricted stubs for requested hidden assets.
type WalletHistoryServiceServer interface {
	GetWalletHistorySummary(context.Context, *GetWalletHistorySummaryRequest) (*GetWalletHistorySummaryResponse, error)
	GetWalletHistoryChart(context.Context, *GetWalletHistoryChartRequest) (*GetWalletHistoryChartResponse, error)
	mustEmbedUnimplementedWalletHistoryServiceServer()
}

// UnimplementedWalletHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletHistoryServiceServer struct{}

func (UnimplementedWalletHistoryServiceServer) GetWalletHistorySummary(context.Context, *GetWalletHistorySummaryRequest) (*GetWalletHistorySummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletHistorySummary not implemented")
}
func (UnimplementedWalletHistoryServiceServer) GetWalletHistoryChart(context.Context, *GetWalletHistoryChartRequest) (*GetWalletHistoryChartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletHistoryChart not implemented")
}
func (UnimplementedWalletHistoryServiceServer) mustEmbedUnimplementedWalletHistoryServiceServer() {}
func (UnimplementedWalletHistoryServiceServer) testEmbeddedByValue()                              {}

// UnsafeWalletHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletHistoryServiceServer will
// result in compilation errors.
type UnsafeWalletHistoryServiceServer interface {
	mustEmbedUnimplementedWalletHistoryServiceServer()
}

func RegisterWalletHistoryServiceServer(s grpc.ServiceRegistrar, srv WalletHistoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedWalletHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletHistoryService_ServiceDesc, srv)
}

func _WalletHistoryService_GetWalletHistorySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletHistorySummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletHistoryServiceServer).GetWalletHistorySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletHistoryService_GetWalletHistorySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletHistoryServiceServer).GetWalletHistorySummary(ctx, req.(*GetWalletHistorySummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletHistoryService_GetWalletHistoryChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletHistoryChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletHistoryServiceServer).GetWalletHistoryChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletHistoryService_GetWalletHistoryChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletHistoryServiceServer).GetWalletHistoryChart(ctx, req.(*GetWalletHistoryChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletHistoryService_ServiceDesc is the grpc.ServiceDesc for WalletHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commercial.WalletHistoryService",
	HandlerType: (*WalletHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWalletHistorySummary",
			Handler:    _WalletHistoryService_GetWalletHistorySummary_Handler,
		},
		{
			MethodName: "GetWalletHistoryChart",
			Handler:    _WalletHistoryService_GetWalletHistoryChart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commercial.proto",
}
