// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: commercial.proto

package commercial

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Psc           float64                `protobuf:"fixed64,3,opt,name=psc,proto3" json:"psc,omitempty"`
	Irr           float64                `protobuf:"fixed64,4,opt,name=irr,proto3" json:"irr,omitempty"`
	Red           float64                `protobuf:"fixed64,5,opt,name=red,proto3" json:"red,omitempty"`
	Blue          float64                `protobuf:"fixed64,6,opt,name=blue,proto3" json:"blue,omitempty"`
	Yellow        float64                `protobuf:"fixed64,7,opt,name=yellow,proto3" json:"yellow,omitempty"`
	Satisfaction  float64                `protobuf:"fixed64,8,opt,name=satisfaction,proto3" json:"satisfaction,omitempty"`
	Effect        float64                `protobuf:"fixed64,9,opt,name=effect,proto3" json:"effect,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_commercial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Wallet) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Wallet) GetPsc() float64 {
	if x != nil {
		return x.Psc
	}
	return 0
}

func (x *Wallet) GetIrr() float64 {
	if x != nil {
		return x.Irr
	}
	return 0
}

func (x *Wallet) GetRed() float64 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *Wallet) GetBlue() float64 {
	if x != nil {
		return x.Blue
	}
	return 0
}

func (x *Wallet) GetYellow() float64 {
	if x != nil {
		return x.Yellow
	}
	return 0
}

func (x *Wallet) GetSatisfaction() float64 {
	if x != nil {
		return x.Satisfaction
	}
	return 0
}

func (x *Wallet) GetEffect() float64 {
	if x != nil {
		return x.Effect
	}
	return 0
}

func (x *Wallet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Wallet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // VARCHAR UUID (TR-xxxxx)
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"` // deposit, withdraw
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Token         int64                  `protobuf:"varint,7,opt,name=token,proto3" json:"token,omitempty"`
	RefId         int64                  `protobuf:"varint,8,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	PayableType   string                 `protobuf:"bytes,9,opt,name=payable_type,json=payableType,proto3" json:"payable_type,omitempty"`
	PayableId     uint64                 `protobuf:"varint,10,opt,name=payable_id,json=payableId,proto3" json:"payable_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_commercial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Transaction) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Transaction) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Transaction) GetToken() int64 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *Transaction) GetRefId() int64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *Transaction) GetPayableType() string {
	if x != nil {
		return x.PayableType
	}
	return ""
}

func (x *Transaction) GetPayableId() uint64 {
	if x != nil {
		return x.PayableId
	}
	return 0
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_commercial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Order) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Order) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RefId         int64                  `protobuf:"varint,3,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	CardPan       string                 `protobuf:"bytes,4,opt,name=card_pan,json=cardPan,proto3" json:"card_pan,omitempty"`
	Gateway       string                 `protobuf:"bytes,5,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Amount        float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Product       string                 `protobuf:"bytes,7,opt,name=product,proto3" json:"product,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_commercial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{3}
}

func (x *Payment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Payment) GetRefId() int64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *Payment) GetCardPan() string {
	if x != nil {
		return x.CardPan
	}
	return ""
}

func (x *Payment) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_commercial_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{4}
}

func (x *GetWalletRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type WalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Psc           string                 `protobuf:"bytes,1,opt,name=psc,proto3" json:"psc,omitempty"`
	Irr           string                 `protobuf:"bytes,2,opt,name=irr,proto3" json:"irr,omitempty"`
	Red           string                 `protobuf:"bytes,3,opt,name=red,proto3" json:"red,omitempty"`
	Blue          string                 `protobuf:"bytes,4,opt,name=blue,proto3" json:"blue,omitempty"`
	Yellow        string                 `protobuf:"bytes,5,opt,name=yellow,proto3" json:"yellow,omitempty"`
	Satisfaction  string                 `protobuf:"bytes,6,opt,name=satisfaction,proto3" json:"satisfaction,omitempty"`
	Effect        float64                `protobuf:"fixed64,7,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_commercial_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{5}
}

func (x *WalletResponse) GetPsc() string {
	if x != nil {
		return x.Psc
	}
	return ""
}

func (x *WalletResponse) GetIrr() string {
	if x != nil {
		return x.Irr
	}
	return ""
}

func (x *WalletResponse) GetRed() string {
	if x != nil {
		return x.Red
	}
	return ""
}

func (x *WalletResponse) GetBlue() string {
	if x != nil {
		return x.Blue
	}
	return ""
}

func (x *WalletResponse) GetYellow() string {
	if x != nil {
		return x.Yellow
	}
	return ""
}

func (x *WalletResponse) GetSatisfaction() string {
	if x != nil {
		return x.Satisfaction
	}
	return ""
}

func (x *WalletResponse) GetEffect() float64 {
	if x != nil {
		return x.Effect
	}
	return 0
}

type DeductBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"` // psc, irr, red, blue, yellow
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductBalanceRequest) Reset() {
	*x = DeductBalanceRequest{}
	mi := &file_commercial_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductBalanceRequest) ProtoMessage() {}

func (x *DeductBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductBalanceRequest.ProtoReflect.Descriptor instead.
func (*DeductBalanceRequest) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{6}
}

func (x *DeductBalanceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeductBalanceRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *DeductBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DeductBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Wallet        *WalletResponse        `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductBalanceResponse) Reset() {
	*x = DeductBalanceResponse{}
	mi := &file_commercial_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductBalanceResponse) ProtoMessage() {}

func (x *DeductBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductBalanceResponse.ProtoReflect.Descriptor instead.
func (*DeductBalanceResponse) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{7}
}

func (x *DeductBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeductBalanceResponse) GetWallet() *WalletResponse {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type AddBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBalanceRequest) Reset() {
	*x = AddBalanceRequest{}
	mi := &file_commercial_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceRequest) ProtoMessage() {}

func (x *AddBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceRequest.ProtoReflect.Descriptor instead.
func (*AddBalanceRequest) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{8}
}

func (x *AddBalanceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddBalanceRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *AddBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Wallet        *WalletResponse        `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBalanceResponse) Reset() {
	*x = AddBalanceResponse{}
	mi := &file_commercial_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceResponse) ProtoMessage() {}

func (x *AddBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceResponse.ProtoReflect.Descriptor instead.
func (*AddBalanceResponse) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{9}
}

func (x *AddBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddBalanceResponse) GetWallet() *WalletResponse {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type LockBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockBalanceRequest) Reset() {
	*x = LockBalanceRequest{}
	mi := &file_commercial_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockBalanceRequest) ProtoMessage() {}

func (x *LockBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockBalanceRequest.ProtoReflect.Descriptor instead.
func (*LockBalanceRequest) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{10}
}

func (x *LockBalanceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LockBalanceRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *LockBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LockBalanceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnlockBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockBalanceRequest) Reset() {
	*x = UnlockBalanceRequest{}
	mi := &file_commercial_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockBalanceRequest) ProtoMessage() {}

func (x *UnlockBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockBalanceRequest.ProtoReflect.Descriptor instead.
func (*UnlockBalanceRequest) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{11}
}

func (x *UnlockBalanceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlockBalanceRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *UnlockBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	StartDateTime string                 `protobuf:"bytes,5,opt,name=start_date_time,json=startDateTime,proto3" json:"start_date_time,omitempty"`
	EndDateTime   string                 `protobuf:"bytes,6,opt,name=end_date_time,json=endDateTime,proto3" json:"end_date_time,omitempty"`
	Status        []int32                `protobuf:"varint,7,rep,packed,name=status,proto3" json:"status,omitempty"`
	Action        string                 `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	Asset         string                 `protobuf:"bytes,9,opt,name=asset,proto3" json:"asset,omitempty"`
	Type          string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_commercial_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{12}
}

func (x *ListTransactionsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListTransactionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListTransactionsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListTransactionsRequest) GetStartDateTime() string {
	if x != nil {
		return x.StartDateTime
	}
	return ""
}

func (x *ListTransactionsRequest) GetEndDateTime() string {
	if x != nil {
		return x.EndDateTime
	}
	return ""
}

func (x *ListTransactionsRequest) GetStatus() []int32 {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListTransactionsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListTransactionsRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *ListTransactionsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionResource `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	HasMorePages  bool                   `protobuf:"varint,3,opt,name=has_more_pages,json=hasMorePages,proto3" json:"has_more_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_commercial_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{13}
}

func (x *ListTransactionsResponse) GetTransactions() []*TransactionResource {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ListTransactionsResponse) GetHasMorePages() bool {
	if x != nil {
		return x.HasMorePages
	}
	return false
}

type TransactionResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Date          string                 `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"` // Jalali format Y/m/d
	Time          string                 `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"` // Jalali format H:m:s
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResource) Reset() {
	*x = TransactionResource{}
	mi := &file_commercial_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResource) ProtoMessage() {}

func (x *TransactionResource) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResource.ProtoReflect.Descriptor instead.
func (*TransactionResource) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{14}
}

func (x *TransactionResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransactionResource) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *TransactionResource) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResource) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TransactionResource) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TransactionResource) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TransactionResource) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type GetLatestTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestTransactionRequest) Reset() {
	*x = GetLatestTransactionRequest{}
	mi := &file_commercial_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestTransactionRequest) ProtoMessage() {}

func (x *GetLatestTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetLatestTransactionRequest) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{15}
}

func (x *GetLatestTransactionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LatestTransactionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LatestTransaction *Transaction           `protobuf:"bytes,1,opt,name=latest_transaction,json=latestTransaction,proto3" json:"latest_transaction,omitempty"`
	LatestPayment     *Payment               `protobuf:"bytes,2,opt,name=latest_payment,json=latestPayment,proto3" json:"latest_payment,omitempty"`
	LatestOrder       *Order                 `protobuf:"bytes,3,opt,name=latest_order,json=latestOrder,proto3" json:"latest_order,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LatestTransactionResponse) Reset() {
	*x = LatestTransactionResponse{}
	mi := &file_commercial_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestTransactionResponse) ProtoMessage() {}

func (x *LatestTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestTransactionResponse.ProtoReflect.Descriptor instead.
func (*LatestTransactionResponse) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{16}
}

func (x *LatestTransactionResponse) GetLatestTransaction() *Transaction {
	if x != nil {
		return x.LatestTransaction
	}
	return nil
}

func (x *LatestTransactionResponse) GetLatestPayment() *Payment {
	if x != nil {
		return x.LatestPayment
	}
	return nil
}

func (x *LatestTransactionResponse) GetLatestOrder() *Order {
	if x != nil {
		return x.LatestOrder
	}
	return nil
}

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	PayableType   string                 `protobuf:"bytes,6,opt,name=payable_type,json=payableType,proto3" json:"payable_type,omitempty"`
	PayableId     uint64                 `protobuf:"varint,7,opt,name=payable_id,json=payableId,proto3" json:"payable_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_commercial_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{17}
}

func (x *CreateTransactionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTransactionRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreateTransactionRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateTransactionRequest) GetPayableType() string {
	if x != nil {
		return x.PayableType
	}
	return ""
}

func (x *CreateTransactionRequest) GetPayableId() uint64 {
	if x != nil {
		return x.PayableId
	}
	return 0
}

type ProcessReferralRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerUserId   uint64                 `protobuf:"varint,1,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessReferralRequest) Reset() {
	*x = ProcessReferralRequest{}
	mi := &file_commercial_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessReferralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessReferralRequest) ProtoMessage() {}

func (x *ProcessReferralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commercial_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessReferralRequest.ProtoReflect.Descriptor instead.
func (*ProcessReferralRequest) Descriptor() ([]byte, []int) {
	return file_commercial_proto_rawDescGZIP(), []int{18}
}

func (x *ProcessReferralRequest) GetBuyerUserId() uint64 {
	if x != nil {
		return x.BuyerUserId
	}
	return 0
}

func (x *ProcessReferralRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ProcessReferralRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *ProcessReferralRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_commercial_proto protoreflect.FileDescriptor

const file_commercial_proto_rawDesc = "" +
	"\n" +
	"\x10commercial.proto\x12\n" +
	"commercial\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc5\x02\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x10\n" +
	"\x03psc\x18\x03 \x01(\x01R\x03psc\x12\x10\n" +
	"\x03irr\x18\x04 \x01(\x01R\x03irr\x12\x10\n" +
	"\x03red\x18\x05 \x01(\x01R\x03red\x12\x12\n" +
	"\x04blue\x18\x06 \x01(\x01R\x04blue\x12\x16\n" +
	"\x06yellow\x18\a \x01(\x01R\x06yellow\x12\"\n" +
	"\fsatisfaction\x18\b \x01(\x01R\fsatisfaction\x12\x16\n" +
	"\x06effect\x18\t \x01(\x01R\x06effect\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf9\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x14\n" +
	"\x05token\x18\a \x01(\x03R\x05token\x12\x15\n" +
	"\x06ref_id\x18\b \x01(\x03R\x05refId\x12!\n" +
	"\fpayable_type\x18\t \x01(\tR\vpayableType\x12\x1d\n" +
	"\n" +
	"payable_id\x18\n" +
	" \x01(\x04R\tpayableId\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb1\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xeb\x01\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x15\n" +
	"\x06ref_id\x18\x03 \x01(\x03R\x05refId\x12\x19\n" +
	"\bcard_pan\x18\x04 \x01(\tR\acardPan\x12\x18\n" +
	"\agateway\x18\x05 \x01(\tR\agateway\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x18\n" +
	"\aproduct\x18\a \x01(\tR\aproduct\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"+\n" +
	"\x10GetWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\xae\x01\n" +
	"\x0eWalletResponse\x12\x10\n" +
	"\x03psc\x18\x01 \x01(\tR\x03psc\x12\x10\n" +
	"\x03irr\x18\x02 \x01(\tR\x03irr\x12\x10\n" +
	"\x03red\x18\x03 \x01(\tR\x03red\x12\x12\n" +
	"\x04blue\x18\x04 \x01(\tR\x04blue\x12\x16\n" +
	"\x06yellow\x18\x05 \x01(\tR\x06yellow\x12\"\n" +
	"\fsatisfaction\x18\x06 \x01(\tR\fsatisfaction\x12\x16\n" +
	"\x06effect\x18\a \x01(\x01R\x06effect\"]\n" +
	"\x14DeductBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"\x7f\n" +
	"\x15DeductBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x06wallet\x18\x03 \x01(\v2\x1a.commercial.WalletResponseR\x06wallet\"Z\n" +
	"\x11AddBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"|\n" +
	"\x12AddBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x06wallet\x18\x03 \x01(\v2\x1a.commercial.WalletResponseR\x06wallet\"s\n" +
	"\x12LockBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"]\n" +
	"\x14UnlockBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"\x9f\x02\n" +
	"\x17ListTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12&\n" +
	"\x0fstart_date_time\x18\x05 \x01(\tR\rstartDateTime\x12\"\n" +
	"\rend_date_time\x18\x06 \x01(\tR\vendDateTime\x12\x16\n" +
	"\x06status\x18\a \x03(\x05R\x06status\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action\x12\x14\n" +
	"\x05asset\x18\t \x01(\tR\x05asset\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\"\xa8\x01\n" +
	"\x18ListTransactionsResponse\x12C\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1f.commercial.TransactionResourceR\ftransactions\x12!\n" +
	"\fcurrent_page\x18\x02 \x01(\x05R\vcurrentPage\x12$\n" +
	"\x0ehas_more_pages\x18\x03 \x01(\bR\fhasMorePages\"\xbf\x01\n" +
	"\x13TransactionResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x12\n" +
	"\x04date\x18\a \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\b \x01(\tR\x04time\"6\n" +
	"\x1bGetLatestTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\xd5\x01\n" +
	"\x19LatestTransactionResponse\x12F\n" +
	"\x12latest_transaction\x18\x01 \x01(\v2\x17.commercial.TransactionR\x11latestTransaction\x12:\n" +
	"\x0elatest_payment\x18\x02 \x01(\v2\x13.commercial.PaymentR\rlatestPayment\x124\n" +
	"\flatest_order\x18\x03 \x01(\v2\x11.commercial.OrderR\vlatestOrder\"\xd3\x01\n" +
	"\x18CreateTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12!\n" +
	"\fpayable_type\x18\x06 \x01(\tR\vpayableType\x12\x1d\n" +
	"\n" +
	"payable_id\x18\a \x01(\x04R\tpayableId\"\x85\x01\n" +
	"\x16ProcessReferralRequest\x12\"\n" +
	"\rbuyer_user_id\x18\x01 \x01(\x04R\vbuyerUserId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount2\x8b\x03\n" +
	"\rWalletService\x12E\n" +
	"\tGetWallet\x12\x1c.commercial.GetWalletRequest\x1a\x1a.commercial.WalletResponse\x12T\n" +
	"\rDeductBalance\x12 .commercial.DeductBalanceRequest\x1a!.commercial.DeductBalanceResponse\x12K\n" +
	"\n" +
	"AddBalance\x12\x1d.commercial.AddBalanceRequest\x1a\x1e.commercial.AddBalanceResponse\x12E\n" +
	"\vLockBalance\x12\x1e.commercial.LockBalanceRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\rUnlockBalance\x12 .commercial.UnlockBalanceRequest\x1a\x16.google.protobuf.Empty2\xaf\x02\n" +
	"\x12TransactionService\x12]\n" +
	"\x10ListTransactions\x12#.commercial.ListTransactionsRequest\x1a$.commercial.ListTransactionsResponse\x12f\n" +
	"\x14GetLatestTransaction\x12'.commercial.GetLatestTransactionRequest\x1a%.commercial.LatestTransactionResponse\x12R\n" +
	"\x11CreateTransaction\x12$.commercial.CreateTransactionRequest\x1a\x17.commercial.Transaction2`\n" +
	"\x0fReferralService\x12M\n" +
	"\x0fProcessReferral\x12\".commercial.ProcessReferralRequest\x1a\x16.google.protobuf.EmptyB\x1eZ\x1cmetarang/shared/pb/commercialb\x06proto3"

var (
	file_commercial_proto_rawDescOnce sync.Once
	file_commercial_proto_rawDescData []byte
)

func file_commercial_proto_rawDescGZIP() []byte {
	file_commercial_proto_rawDescOnce.Do(func() {
		file_commercial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commercial_proto_rawDesc), len(file_commercial_proto_rawDesc)))
	})
	return file_commercial_proto_rawDescData
}

var file_commercial_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_commercial_proto_goTypes = []any{
	(*Wallet)(nil),                      // 0: commercial.Wallet
	(*Transaction)(nil),                 // 1: commercial.Transaction
	(*Order)(nil),                       // 2: commercial.Order
	(*Payment)(nil),                     // 3: commercial.Payment
	(*GetWalletRequest)(nil),            // 4: commercial.GetWalletRequest
	(*WalletResponse)(nil),              // 5: commercial.WalletResponse
	(*DeductBalanceRequest)(nil),        // 6: commercial.DeductBalanceRequest
	(*DeductBalanceResponse)(nil),       // 7: commercial.DeductBalanceResponse
	(*AddBalanceRequest)(nil),           // 8: commercial.AddBalanceRequest
	(*AddBalanceResponse)(nil),          // 9: commercial.AddBalanceResponse
	(*LockBalanceRequest)(nil),          // 10: commercial.LockBalanceRequest
	(*UnlockBalanceRequest)(nil),        // 11: commercial.UnlockBalanceRequest
	(*ListTransactionsRequest)(nil),     // 12: commercial.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),    // 13: commercial.ListTransactionsResponse
	(*TransactionResource)(nil),         // 14: commercial.TransactionResource
	(*GetLatestTransactionRequest)(nil), // 15: commercial.GetLatestTransactionRequest
	(*LatestTransactionResponse)(nil),   // 16: commercial.LatestTransactionResponse
	(*CreateTransactionRequest)(nil),    // 17: commercial.CreateTransactionRequest
	(*ProcessReferralRequest)(nil),      // 18: commercial.ProcessReferralRequest
	(*timestamppb.Timestamp)(nil),       // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 20: google.protobuf.Empty
}
var file_commercial_proto_depIdxs = []int32{
	19, // 0: commercial.Wallet.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: commercial.Wallet.updated_at:type_name -> google.protobuf.Timestamp
	19, // 2: commercial.Transaction.created_at:type_name -> google.protobuf.Timestamp
	19, // 3: commercial.Transaction.updated_at:type_name -> google.protobuf.Timestamp
	19, // 4: commercial.Order.created_at:type_name -> google.protobuf.Timestamp
	19, // 5: commercial.Payment.created_at:type_name -> google.protobuf.Timestamp
	5,  // 6: commercial.DeductBalanceResponse.wallet:type_name -> commercial.WalletResponse
	5,  // 7: commercial.AddBalanceResponse.wallet:type_name -> commercial.WalletResponse
	14, // 8: commercial.ListTransactionsResponse.transactions:type_name -> commercial.TransactionResource
	1,  // 9: commercial.LatestTransactionResponse.latest_transaction:type_name -> commercial.Transaction
	3,  // 10: commercial.LatestTransactionResponse.latest_payment:type_name -> commercial.Payment
	2,  // 11: commercial.LatestTransactionResponse.latest_order:type_name -> commercial.Order
	4,  // 12: commercial.WalletService.GetWallet:input_type -> commercial.GetWalletRequest
	6,  // 13: commercial.WalletService.DeductBalance:input_type -> commercial.DeductBalanceRequest
	8,  // 14: commercial.WalletService.AddBalance:input_type -> commercial.AddBalanceRequest
	10, // 15: commercial.WalletService.LockBalance:input_type -> commercial.LockBalanceRequest
	11, // 16: commercial.WalletService.UnlockBalance:input_type -> commercial.UnlockBalanceRequest
	12, // 17: commercial.TransactionService.ListTransactions:input_type -> commercial.ListTransactionsRequest
	15, // 18: commercial.TransactionService.GetLatestTransaction:input_type -> commercial.GetLatestTransactionRequest
	17, // 19: commercial.TransactionService.CreateTransaction:input_type -> commercial.CreateTransactionRequest
	18, // 20: commercial.ReferralService.ProcessReferral:input_type -> commercial.ProcessReferralRequest
	5,  // 21: commercial.WalletService.GetWallet:output_type -> commercial.WalletResponse
	7,  // 22: commercial.WalletService.DeductBalance:output_type -> commercial.DeductBalanceResponse
	9,  // 23: commercial.WalletService.AddBalance:output_type -> commercial.AddBalanceResponse
	20, // 24: commercial.WalletService.LockBalance:output_type -> google.protobuf.Empty
	20, // 25: commercial.WalletService.UnlockBalance:output_type -> google.protobuf.Empty
	13, // 26: commercial.TransactionService.ListTransactions:output_type -> commercial.ListTransactionsResponse
	16, // 27: commercial.TransactionService.GetLatestTransaction:output_type -> commercial.LatestTransactionResponse
	1,  // 28: commercial.TransactionService.CreateTransaction:output_type -> commercial.Transaction
	20, // 29: commercial.ReferralService.ProcessReferral:output_type -> google.protobuf.Empty
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_commercial_proto_init() }
func file_commercial_proto_init() {
	if File_commercial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commercial_proto_rawDesc), len(file_commercial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_commercial_proto_goTypes,
		DependencyIndexes: file_commercial_proto_depIdxs,
		MessageInfos:      file_commercial_proto_msgTypes,
	}.Build()
	File_commercial_proto = out.File
	file_commercial_proto_goTypes = nil
	file_commercial_proto_depIdxs = nil
}
